apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: registry.cn-hangzhou.aliyuncs.com/weiwendi/tomcat:latest
        ports:
        - containerPort: 8080
---
#service
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat

---
#ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tomcat
spec:
  tls:
  - hosts: 
    - aiops.red
    secretName: ingress-secret
  rules:
  - host: aiops.red
    http:
      paths:
      - path: /tomcat
        backend:
          serviceName: tomcat
          servicePort: 80
