- name: Deploy kubernetes cluster
  hosts: k8sm
# 
# Deploy kubernetes master
  tasks:
  - name: Distribute kubernetes binaries
    copy:
      src: /tmp/kubernetes/server/bin/kube-controller-manager
      dest: /usr/local/bin/
      mode: 0755
#
# SCP CA and private key
  - name: cp ca and private key
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
    - {src: '../pki/kube-controller-manager/controller-manager.csr', dest: '/etc/kubernetes/pki/'}
    - {src: '../pki/kube-controller-manager/controller-manager.pem', dest: '/etc/kubernetes/pki/'}
    - {src: '../pki/kube-controller-manager/controller-manager-key.pem', dest: '/etc/kubernetes/pki/'}
#
# SCP kubeconfig file.
  - name: cp kubeconfig file
    copy:
      src: ../pki/kube-controller-manager/kube-controller-manager.kubeconfig
      dest: /etc/kubernetes/
#
# SCP service files
  - name: cp kube-controller-manager.service
    copy:
      src: kube-controller-manager.service
      dest: /usr/lib/systemd/system/kube-controller-manager.service
#
# Started services
  - name: started kube-controller-manager.service
    service:
      name: kube-controller-manager
      daemon-reload: yes
      state: started
      enabled: yes
